Vagrant.configure("2") do |config|
  config.vm.box = "pandas"
  config.vm.box_url = "http://dl.dropbox.com/u/29645873/vagrants/pandas.box"

  config.ssh.forward_x11 = true

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.name = "pandas"
    # virtualbox.gui = true
  end

  config.vm.network :forwarded_port, guest: 8888, host: 8888
end
