Vagrant.configure("2") do |config|
  config.vm.box = "mysql"
  config.vm.box_url = "http://dl.dropbox.com/u/29645873/vagrants/mysql.box"

  config.ssh.forward_x11 = true

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.name = "mysql"
    # virtualbox.gui = true
  end

  config.vm.network :forwarded_port, guest: 3306, host: 3306
end
