Vagrant.configure("2") do |config|
  config.vm.box = "nginx"
  config.vm.box_url = "http://dl.dropbox.com/u/29645873/vagrants/nginx.box"

  config.ssh.forward_x11 = true

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.name = "nginx"
    # virtualbox.gui = true
  end

  config.vm.network :forwarded_port, guest: 80, host: 8000
end
