Vagrant::Config.run do |config|
  config.vm.box = "nginx"
  config.vm.box_url = "http://dl.dropbox.com/u/29645873/vagrants/nginx.box"

  # config.vm.boot_mode = :gui
  config.ssh.forward_x11 = true

  config.vm.forward_port 80, 8000
end
