Vagrant.configure("2") do |config|
  config.vm.box = "refine"
  config.vm.box_url = "http://dl.dropbox.com/u/29645873/vagrants/refine.box"

  config.ssh.forward_x11 = true

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.name = "refine"
    # virtualbox.gui = true
  end

  config.vm.network :forwarded_port, guest: 3333, host: 3333
end
