Vagrant::Config.run do |config|
  config.vm.box = "refine"
  config.vm.box_url = "http://dl.dropbox.com/u/29645873/vagrants/refine.box"

  # config.vm.boot_mode = :gui
  config.ssh.forward_x11 = true

  config.vm.forward_port 3333, 3333
end
