Vagrant.configure("2") do |config|
  config.vm.box = "r"
  config.vm.box_url = "http://dl.dropbox.com/u/29645873/vagrants/r.box"

  config.ssh.forward_x11 = true

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.name = "r"
    # virtualbox.gui = true
  end
end
